### ISSUE TITLE
Macros \cyrmath.. are not supported anymore

### ISSUE THREAD

**Issue by ivankokan** [andrewshadura/babel-belarusian#1]
https://github.com/andrewshadura/babel-belarusian/blob/7fc06488807d2c371d00fe2757f2131416f86f66/belarusian.dtx#L1955

As of version 1.2 the macros `\cyrmath..` are not supported any more. They
require package `\pkg{textmath}` which is not available now. Instead of
`\cyrmath..` it is advised to use corresponding `\text..` commands; they
do work in math mode.

So, `\textnormal` will do in these 9 lines (as in `russian`).

**Comment by andrewshadura** [comment]
Thanks!

**Comment by ivankokan** [comment]
Hi, any estimations for the official CTAN release? (I guess version number, change log etc. must be updated as well.)

**Comment by andrewshadura** [comment]
Maybe tomorrow?

**Comment by ivankokan** [comment]
Not that urgent. :)
