### ISSUE TITLE
Памылка генерацыі зместа праз pdflatex

### ISSUE THREAD

**Issue by measles** [andrewshadura/babel-belarusian#3]
Пры гэнерацыі PDF з дапамогай `pdflatex` кірылічныя сімвалы не адлюстроўваюцца, калі асноўнай мовай для babel стаіць беларуская. 
![выява](https://user-images.githubusercontent.com/510043/111633565-b30bac00-8806-11eb-93be-045b4703aa0a.png)

Той жа файл з рускай у якасці асноўнай генераць кантэнт без аніякіх цяжкасцяў.

На чым атрымаў памылку: 
* Debian bullseye, 
* texlive, 
* babel, 
* babel-belarusian 2018/10/09 1.5

Прыклад коду, які выклікае памылку [тут](https://github.com/measles/error_sample).

**Comment by measles** [comment]
@andrewshadura Ёсць некія навіны пра гэтую бяду?

**Comment by measles** [comment]
@andrewshadura Не глядзеў?

**Comment by andrewshadura** [comment]
Паглядзеў. Ня ведаю, што я раблю ня так, але атрымаўся PDF з нармальнымі літарамі ў TOC
![image](https://user-images.githubusercontent.com/309253/142778783-d6b2cb44-c72b-4bc1-ae92-f59db178b536.png)

[sample.pdf](https://github.com/andrewshadura/babel-belarusian/files/7577089/sample.pdf)
[sample.log](https://github.com/andrewshadura/babel-belarusian/files/7577092/sample.log)
[sample.aux](https://github.com/andrewshadura/babel-belarusian/files/7577096/sample.aux.txt)
[sample.out](https://github.com/andrewshadura/babel-belarusian/files/7577099/sample.out.txt)
[sample.toc](https://github.com/andrewshadura/babel-belarusian/files/7577100/sample.toc.txt)

**Comment by measles** [comment]
тады нешта раблю не так я. :) Дзякуй!

**Comment by andrewshadura** [comment]
Можа не, можа быў нейкі баг недзе, які ўжо пафіксілі :slightly_smiling_face:

**Comment by measles** [comment]
Я праверу са свайго боку.

**Comment by measles** [comment]
Паспрабаваў на чыстай свежаўсталяванай сістэме (Debian stable). Усё тое ж самае. Раз памылка з майго боку, то я закрыю баг.
